### ISSUE TITLE
pin requirements

### ISSUE THREAD

**Issue by andrewkern** [kr-colab/popgen-npe#31]
currently the `requirements.yaml` file looks like this:

```yaml
name: popgensbi_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # comment this out if cuda isn't available
  - stdpopsim
  - msprime
  - dadi
  - defopt
  - snakemake
  - zuko
  - pip
  - pip:
    - sbi==v0.22.0
    - dinf
    - snakemake-executor-plugin-slurm
    - natsort
    - moments-popgen
```

i think we should pin versions of a few things here. in particular, I think we should pin versions of  `python`,`snakemake`, and `msprime`. anything else?
